objects/Assigned_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assign_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Milestone 1</fullName>
                </value>
                <value>
                    <fullName>Milestone 2</fullName>
                </value>
                <value>
                    <fullName>Milestone 3</fullName>
                </value>
                <value>
                    <fullName>Milestone 4</fullName>
                </value>
                <value>
                    <fullName>Milestone 5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Onboarding_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Trail</label>
        <referenceTo>Onboarding_Program__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Assigned_Tasks_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assigned Trail/Step</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Assigned Trail/Step Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Trails/Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Onboarding_Program__c.object
<CustomObject>
    <label>Onboarding Trail</label>
    <nameField>
        <label>Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Onboarding_Program_User_Role_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Onboarding_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Trail</label>
        <referenceTo>Onboarding_Program__c</referenceTo>
        <relationshipLabel>Onboarding Trail - User Role Junctions</relationshipLabel>
        <relationshipName>Program_User_Role_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Role</label>
        <referenceTo>User_Role__c</referenceTo>
        <relationshipName>Program_User_Role_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Onboarding Trail - User Role Junction</label>
    <nameField>
        <displayFormat>PUR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Trail - User Role Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Role__c.object
<CustomObject>
    <label>User Role</label>
    <nameField>
        <label>User Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_User_Role_Junction__c.object
<CustomObject>
    <fields>
        <fullName>User_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Role</label>
        <referenceTo>User_Role__c</referenceTo>
        <relationshipLabel>Users</relationshipLabel>
        <relationshipName>User_User_Role_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User - User Role Junction</label>
    <nameField>
        <displayFormat>UUR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User - User Role Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AssignProgramsCntr_Test.cls
 /*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 * Test class for AssignProgramCntr
 */ 
@IsTest
public with sharing class AssignProgramsCntr_Test {
    
    static testMethod void validate_getPrograms(){
        User_Role__c lUserRole = TestDataUtil.getUserRole('Software Engineer');
        insert lUserRole;
        List<Onboarding_Program__c> onboardingPrograms = TestDataUtil.getOnboardingPrograms(3);
        insert onboardingPrograms;
        User luser = [SELECT Id FROM User LIMIT 1];
        if(onboardingPrograms.size()>0){ 
            User_User_Role_Junction__c userUserRoleJunction = TestDataUtil.assignUserRoleToUser(lUser.Id,lUserRole.Id);
            insert userUserRoleJunction;
            Assigned_Task__c assignedProgram = TestDataUtil.assignProgramToUser(onboardingPrograms.get(0).Id,lUser.Id);
            insert assignedProgram;
            Onboarding_Program_User_Role_Junction__c userRoleProgramJunction = 
                TestDataUtil.assignUserRoleToProgram(lUserRole.Id,onboardingPrograms.get(1).Id);   
            insert userRoleProgramJunction;
        }
        Map<String,List<Onboarding_Program__c>> programsMap = AssignProgramsCntr.getPrograms(lUser.Id);
        System.assertEquals(2,programsMap.get('ALL').size());
        System.assertEquals(1,programsMap.get('RECOMMENDED').size());
    }
    
    static testMethod void validate_assignPrograms(){
        List<String> programIds = new List<String>();
        List<Onboarding_Program__c> onboardingPrograms = TestDataUtil.getOnboardingPrograms(3);
        insert onboardingPrograms;
        for(Onboarding_Program__c onboardingProgram : onboardingPrograms){
            programIds.add(onboardingProgram.Id);
        }
        User luser = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' LIMIT 1];
        List<Assigned_Task__c> programsToAssign = new List<Assigned_Task__c>();
        for(String programId : programIds){
            programsToAssign.add(new Assigned_Task__c(
                Onboarding_Program__c  = programId,
                Assign_To__c  = luser.Id,
                Milestone__c = 'Milestone 1'
            ));
        }
        AssignProgramsCntr.assignPrograms(JSON.serialize(programsToAssign));
        List<Assigned_Task__c> assignedPrograms = [SELECT Id FROM Assigned_Task__c WHERE Onboarding_Program__c IN :programIds];
        System.assertEquals(3,assignedPrograms.size());
    }
    
    static testMethod void validate_getMilestones(){
        List<DataUtil.CustomPicklistRecord> milestones = AssignProgramsCntr.getMilestones();
        System.assert(milestones.size()>0);
        
    }
}