objects/Assigned_Task__c.object
<CustomObject>
    <fields>
        <fullName>Energizers__c</fullName>
        <label>Energizers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Feedback__c</fullName>
        <label>Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Onboarding_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Trail</label>
        <referenceTo>Onboarding_Program__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Assigned_Tasks_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Assigned_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Assigned Trail</label>
        <referenceTo>Assigned_Task__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Child_Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Reopen__c</fullName>
        <label>Reason for Reopen</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assigned_Task_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Assigned Trail/Step</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Assigned Trail/Step Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Trails/Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/On_boarding_Task__c.object
<CustomObject>
    <label>Onboarding Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Steps</pluralLabel>
    <recordTypes>
        <fullName>Operational</fullName>
        <active>true</active>
        <label>Operational</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Onboarding_Program__c.object
<CustomObject>
    <label>Onboarding Trail</label>
    <nameField>
        <label>Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Energizers__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Energizers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

globalValueSets/Assigned_Task_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>In-Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <masterLabel>Assigned Task Status</masterLabel>
</GlobalValueSet>

classes/AssignedTaskProgram_Test.cls
 /*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 * Test class for AssignedTaskProgram_Trigger 
 */
@isTest
public without sharing class AssignedTaskProgram_Test {

    static testMethod void validate_AssignTaskProgram(){
        User lUser = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' LIMIT 1];
        List<On_boarding_Task__c> onboardingTask = TestDataUtil.getOnboardingTasks(1);
        onboardingTask.get(0).RecordTypeId = Schema.SObjectType.On_boarding_Task__c.getRecordTypeInfosByName().get('Operational').getRecordTypeId();
        insert onboardingTask;
        List<Onboarding_Program__c> onboardingProgram = TestDataUtil.getOnboardingPrograms(1);
        insert onboardingProgram;
        Assigned_Task__c assignedProgram = TestDataUtil.assignProgramToUser(onboardingProgram.get(0).Id,lUser.Id);
        insert assignedProgram;
        List<Assigned_Task__c> assignedTasks = TestDataUtil.getAssignedTask(onboardingTask);
        assignedTasks.get(0).Status__c = 'New';
        assignedTasks.get(0).Parent_Assigned_Task__c = assignedProgram.Id;
        insert assignedTasks;
        assignedTasks.get(0).Status__c = 'Completed';  
        update assignedTasks.get(0);
        Assigned_Task__c assignedProgram_1 = TestDataUtil.assignProgramToUser(onboardingProgram.get(0).Id,lUser.Id);
        assignedProgram_1.Status__c = 'New';
        insert assignedProgram_1;
        assignedProgram_1.Status__c = 'Completed';
        update assignedProgram_1;
        assignedProgram_1.Feedback__c = 'Test Feedback';
        update assignedProgram_1;
        List<On_boarding_Task__c> onboardingTask_1 = TestDataUtil.getOnboardingTasks(1);
        insert onboardingTask_1;
        List<Assigned_Task__c> assignedTasks_1 = TestDataUtil.getAssignedTask(onboardingTask_1);
        assignedTasks_1.get(0).Status__c = 'New';
        insert assignedTasks_1.get(0);
        assignedTasks_1.get(0).Status__c = 'Completed';
        update assignedTasks_1.get(0); 
        assignedTasks_1.get(0).Status__c = 'In-Progress';
        assignedTasks_1.get(0).Reason_for_Reopen__c = 'Reopened the task';
        update assignedTasks_1.get(0);
        assignedTasks_1.get(0).Status__c = 'Closed';
        update assignedTasks_1.get(0);
        User updatedUser = [SELECT Id, Energizers__c FROM User WHERE Id = :lUser.Id];
        System.assertEquals(100, updatedUser.Energizers__c);
    }
}