objects/Assigned_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assign_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Today__c</fullName>
        <formula>DATEVALUE( Target_Date_Time__c) == Today()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Today</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Assigned_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Assigned Trail</label>
        <referenceTo>Assigned_Task__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Child_Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assigned_Task_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Date_Time__c</fullName>
        <label>Target Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Step</label>
        <referenceTo>On_boarding_Task__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assigned Trail/Step</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Assigned Trail/Step Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Trails/Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Assigned_Task_Contribution__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Assigned Trail/Step Contribution</label>
    <nameField>
        <displayFormat>ATC-{0000}</displayFormat>
        <label>Contribution ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Trail/Step Contributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/On_boarding_Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <label>Onboarding Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Steps</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <label>Business</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Assigned_Task_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>In-Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <masterLabel>Assigned Task Status</masterLabel>
</GlobalValueSet>

classes/MenteesTaskCntr.cls
/**
* Controller for Mentees Task Lightning Component
**/
public with sharing class MenteesTaskCntr {
    
    /**
* Aura function to return all assigned tasks for the logged in user (Mentee) categorized with Status 
**/
    @AuraEnabled
    public static Map<String,List<object>> getInitData(){
        Map<String,List<object>> initDataMap = new Map<String,List<object>>();
        List<AssignedTasksWrapper> assignedTasksWrappers = new List<AssignedTasksWrapper>();
        String userId = UserInfo.getUserId();
        List<Assigned_Task__c> thisMonthDue = new List<Assigned_Task__c>();
        List<Assigned_Task__c> inProgress = new List<Assigned_Task__c>();
        List<Assigned_Task__c> completed = new List<Assigned_Task__c>();
        RecordTypeInfo  businessRecordTypeInfo = Schema.SObjectType.On_boarding_Task__c.getRecordTypeInfosByName().get('Business');
        if(businessRecordTypeInfo.isAvailable()){
            Id businessRecordTypeId = businessRecordTypeInfo.getRecordTypeId();
            List<String> fieldNames_AT = new List<String>();
            fieldNames_AT.add('Due_Today__c');
            fieldNames_AT.add('Target_Date_Time__c');
            fieldNames_AT.add('Task__c');
            fieldNames_AT.add('Status__c');
            fieldNames_AT.add('Assign_To__c');
            List<String> fieldNameTK = new List<String>();
            fieldNameTK.add('Name');
            fieldNameTK.add('Link__c');
            fieldNameTK.add('Task_Due_Date__c');
            fieldNameTK.add('Description__c');
            if(FLSCheck.isAccessible(fieldNames_AT,'Assigned_Task__c') && FLSCheck.isAccessible(fieldNameTK,'On_boarding_Task__c')){
                List<Assigned_Task__c> assignedTasks = [SELECT Id
                                                             ,Due_Today__c,Target_Date_Time__c , 
                                                              Task__r.Name,Task__r.Link__c,Task__r.Description__c ,Status__c,(SELECT Id FROM Child_Assigned_Tasks__r) 
                                                              FROM Assigned_Task__c WHERE Status__c != 'Cancelled' AND Assign_To__c = :userId AND (Task__c =null OR Task__r.RecordTypeId =  :businessRecordTypeId)];
                for(Assigned_Task__c assignedTask : assignedTasks){
                    if(assignedTask.Child_Assigned_Tasks__r.size() == 0){
                        if(assignedTask.Target_Date_Time__c!=null && assignedTask.Target_Date_Time__c.month() == System.today().month() && assignedTask.Status__c == 'New'){
                            thisMonthDue.add(assignedTask);
                        }else if(assignedTask.Status__c == 'In-Progress'){
                            inProgress.add(assignedTask);
                        }else if(assignedTask.Status__c == 'Completed' || assignedTask.Status__c == 'Closed'){
                            completed.add(assignedTask);
                        }
                    }
                }
                assignedTasksWrappers.add(new AssignedTasksWrapper('This Month\'s Tasks',thisMonthDue,'#e99f63'));
                assignedTasksWrappers.add(new AssignedTasksWrapper('In Progress',inProgress,'#f6ce6f'));
                assignedTasksWrappers.add(new AssignedTasksWrapper('Completed',completed,'#77c8cc'));
            }
            initDataMap.put('KANBAN_DATA',assignedTasksWrappers);
        }
        return initDataMap;
    }
    
    /**
* Aura function to retrieve attachments and task contributions for a particular assigned task.
**/    
    @AuraEnabled
    public static Map<String,List<sObject>> getRecordRelateData(String recordId){
        Map<String,List<sObject>> recordRelateData = new Map<String,List<sObject>>();
        List<String> contentDocumentLinkFields = new List<String>();
        contentDocumentLinkFields.add('ContentDocumentId');
        contentDocumentLinkFields.add('LinkedEntityId');
        if(FLSCheck.isAccessible(contentDocumentLinkFields, 'ContentDocumentLink')){
            recordRelateData.put('ATTACHMENTS',[SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :recordId]);
        }
        List<String> assignedTaskContributionFields = new List<String>();
        assignedTaskContributionFields.add('Date__c');
        assignedTaskContributionFields.add('Comments__c');
        //assignedTaskContributionFields.add('Task__c');
        if(FLSCheck.isAccessible(assignedTaskContributionFields, 'Assigned_Task_Contribution__c')){
            recordRelateData.put('TASKCONTRIBUTION',[SELECT Id,Date__c,Comments__c FROM Assigned_Task_Contribution__c ]);
        }
        return recordRelateData;
    }
    
    /**
*  Wrapper class for storing assigned tasks along with the task type (status) and the header color
**/ 
    public class AssignedTasksWrapper{
        @AuraEnabled
        public String taskType {get; set;}
        @AuraEnabled
        public List<Assigned_Task__c> records {get; set;}
        @AuraEnabled
        public String headingColor{get;set;}
        
        public AssignedTasksWrapper(string taskType,List<sobject> recs,String headingColor){
            this.records = recs;
            this.taskType = taskType;
            this.headingColor = headingColor;
        }
    }
    
    /**
* Aura function to update the status of a particular assigned tasks when user drags and drops the task from the kanban.
**/
    @AuraEnabled
    public static List<AssignedTasksWrapper> updateAssignedTask(String kanbanRecords, String recordToUpdate,String dragCategory, String dropCategory){
        try{
            List<AssignedTasksWrapper> assignedTasks = (List<AssignedTasksWrapper>) JSON.deserialize(kanbanRecords,List<AssignedTasksWrapper>.class);
            Assigned_Task__c draggedTask = (Assigned_Task__c) JSON.deserialize(recordToUpdate,Assigned_Task__c.class);
            if(dropCategory == 'In Progress'){
                draggedTask.Status__c = 'In-Progress';
            }else if(dropCategory == 'Completed'){
                draggedTask.Status__c = 'Completed';
            }
            List<String> fieldNames = new List<String>();
            fieldNames.add('Status__c');
            if(FLSCheck.isUpdateable(fieldNames, 'Assigned_Task__c')){
                update new Assigned_Task__c(Id = draggedTask.Id, Status__c = draggedTask.Status__c);
            }
            for(AssignedTasksWrapper assignedTask : assignedTasks){
                if(assignedTask.taskType == dragCategory){
                    for(Integer i=0;i<assignedTask.records.size();i++){
                        Assigned_Task__c lTaskRecord = assignedTask.records[i];
                        if(lTaskRecord.Id == draggedTask.Id){
                            assignedTask.records.remove(i);
                        }
                    }
                }else if(assignedTask.taskType == dropCategory){
                    assignedTask.records.add(draggedTask);
                }
            }
            return assignedTasks;
        }
        catch(exception e){
            return null;
        }
    }
}