objects/Assigned_Task__c.object
<CustomObject>
    <fields>
        <fullName>Onboarding_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Trail</label>
        <referenceTo>Onboarding_Program__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Assigned_Tasks_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assigned Trail/Step</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Assigned Trail/Step Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Trails/Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Onboarding_Program__c.object
<CustomObject>
    <label>Onboarding Trail</label>
    <nameField>
        <label>Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MenteeProfileCntr_Test.cls
 /*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
@isTest
public with sharing class MenteeProfileCntr_Test {
    
    static testMethod void validate_getMenteeDetailAndAssignmentInfo(){
        User lUser = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator'];
        DataUtil.addMenteePermissionSetToUser(lUser.Id);
        System.runAs(lUser){
            List<Onboarding_Program__c> onboardingPrograms = TestDataUtil.getOnboardingPrograms(3);
            insert onboardingPrograms;
            List<Assigned_Task__c> assignedPrograms = new List<Assigned_Task__c>();
            for(Onboarding_Program__c onboardingProgram : onboardingPrograms){
                assignedPrograms.add(TestDataUtil.assignProgramToUser(onboardingPrograms.get(0).Id,lUser.Id));
            }
            insert assignedPrograms;
            Map<String,Object> menteeDetailAndAssignmentInfo = MenteeProfileCntr.getMenteeDetailAndAssignmentInfo();
            System.assertEquals(1, ((MentorProfileCntr.MenteeAssignmentInfo)menteeDetailAndAssignmentInfo.get('ASSIGNMENT_INFO')).menteeMilestones.size());
            System.assertEquals(lUser.Id, ((User)menteeDetailAndAssignmentInfo.get('MENTEE_INFO')).Id);
        }
     }
}