objects/Assigned_Task__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assigned_Task_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Assigned Trail/Step</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Assigned Trail/Step Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Trails/Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Assigned_Task_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>In-Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <masterLabel>Assigned Task Status</masterLabel>
</GlobalValueSet>

classes/MenteeOpTaskListCntr_Test.cls
/**
*  Test class for the MenteeOpTaskListCntr controller
**/
@isTest
public with sharing class MenteeOpTaskListCntr_Test {
    
	static testMethod void validate_changeStatusOfTask() {
		Assigned_Task__c assignedTask = TestDataUtil.getAssignedTask();
        insert assignedTask;
        Assigned_Task__c aTask = MenteeOpTaskListCntr.changeStatusOfTask(assignedTask);
        System.assertEquals('Completed', aTask.Status__c);
        Assigned_Task__c progTask = MenteeOpTaskListCntr.changeStatusOfTask(aTask);
        System.assertEquals('In-Progress', progTask.Status__c);
    }
    
    static testMethod void validate_getMenteeTasks(){
        List<Assigned_Task__c> aTasks = MenteeOpTaskListCntr.getMenteeTasks();
        System.assertEquals(0, aTasks.size());
    }
}