objects/Assigned_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assign_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Today__c</fullName>
        <formula>DATEVALUE( Target_Date_Time__c) == Today()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Today</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assigned_Task_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Date_Time__c</fullName>
        <label>Target Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Step</label>
        <referenceTo>On_boarding_Task__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assigned Trail/Step</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Assigned Trail/Step Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Trails/Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/On_boarding_Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <label>Onboarding Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Steps</pluralLabel>
    <recordTypes>
        <fullName>Operational</fullName>
        <active>true</active>
        <label>Operational</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Assigned_Task_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>In-Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <masterLabel>Assigned Task Status</masterLabel>
</GlobalValueSet>

classes/MenteeOpTaskListCntr.cls
 /*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 * Controller for MenteeOpTaskList lightning component
 */
public with sharing class MenteeOpTaskListCntr {
    
    /**
*  This function returns all assigned operational tasks for the mentee
**/
    @AuraEnabled
    public static List<Assigned_Task__c> getMenteeTasks(){
        RecordTypeInfo opRecordTypeInfo = Schema.SObjectType.On_boarding_Task__c.getRecordTypeInfosByName().get('Operational');
        if(opRecordTypeInfo.isAvailable()){
            Id opRecordTypeId = opRecordTypeInfo.getRecordTypeId();
            List<String> fieldNames_AT = new List<String>();
            fieldNames_AT.add('Due_Today__c');
            fieldNames_AT.add('Target_Date_Time__c');
            fieldNames_AT.add('Task__c');
            fieldNames_AT.add('Status__c');
            fieldNames_AT.add('Assign_To__c');
            List<String> fieldName_TK = new List<String>();
            fieldName_TK.add('Name');
            fieldName_TK.add('Link__c');
            //fieldName_TK.add('Task_Due_Date__c');
            fieldName_TK.add('Description__c');
            if(FLSCheck.isAccessible(fieldNames_AT,'Assigned_Task__c') && FLSCheck.isAccessible(fieldName_TK,'On_boarding_Task__c')){
                return [SELECT Id,Due_Today__c,Target_Date_Time__c , 
                        Task__r.Name,Task__r.Link__c,
                        Task__r.Description__c ,Status__c
                        FROM Assigned_Task__c WHERE Assign_To__c = :UserInfo.getUserId() 
                        AND Task__c!= null AND Task__r.RecordTypeId =  :opRecordTypeId ORDER BY Status__c ASC];
            }
            else{
                System.debug('ot acceesbile');
            }
        }
        return new List<Assigned_Task__c>();
    }
    
    /**
*  This function updates the status of the task
**/
    @AuraEnabled
    public static Assigned_Task__c changeStatusOfTask(Assigned_Task__c task){
        if(task.Status__c == 'Completed'){
            task.Status__c = 'In-Progress';
        } else if(task.Status__c == 'In-Progress' || task.Status__c == 'New'){
            task.Status__c = 'Completed';
        }
        List<String> fieldNames = new List<String>();
        fieldNames.add('Status__c');
        if(FLSCheck.isUpdateable(fieldNames, 'Assigned_Task__c')){
            update new Assigned_Task__c(Id = task.Id, Status__c = task.Status__c);
        }
        return task;
    }
}