objects/Assigned_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assign_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Value__c</fullName>
        <label>Current Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Energizers__c</fullName>
        <label>Energizers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Feedback__c</fullName>
        <label>Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Medals__c</fullName>
        <label>Medals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Milestone 1</fullName>
                </value>
                <value>
                    <fullName>Milestone 2</fullName>
                </value>
                <value>
                    <fullName>Milestone 3</fullName>
                </value>
                <value>
                    <fullName>Milestone 4</fullName>
                </value>
                <value>
                    <fullName>Milestone 5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Onboarding_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Trail</label>
        <referenceTo>Onboarding_Program__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Assigned_Tasks_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overdue__c</fullName>
        <formula>IF( (TEXT(Status__c) == &apos;In-Progress&apos; || TEXT(Status__c) == &apos;New&apos;) &amp;&amp; (Target_Date_Time__c &lt;  NOW()) ,true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overdue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Assigned_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Assigned Trail</label>
        <referenceTo>Assigned_Task__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Child_Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Percentage_Completed__c</fullName>
        <label>Percentage Completed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Reason_for_Reopen__c</fullName>
        <label>Reason for Reopen</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assigned_Task_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Date_Time__c</fullName>
        <label>Target Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Step</label>
        <referenceTo>On_boarding_Task__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Quantifiable</fullName>
                </value>
                <value>
                    <fullName>Non-quantifiable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assigned Trail/Step</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Assigned Trail/Step Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Trails/Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/On_boarding_Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration_Type__c</fullName>
        <label>Duration Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hour(s)</fullName>
                </value>
                <value>
                    <fullName>Day(s)</fullName>
                </value>
                <value>
                    <fullName>Week(s)</fullName>
                </value>
                <value>
                    <fullName>Month(s)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quantifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Target_Value__c</fullName>
        <label>Target Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Onboarding Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Onboarding_Program__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration_Type__c</fullName>
        <label>Duration Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hour(s)</fullName>
                </value>
                <value>
                    <fullName>Day(s)</fullName>
                </value>
                <value>
                    <fullName>Week(s)</fullName>
                </value>
                <value>
                    <fullName>Month(s)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Onboarding Trail</label>
    <nameField>
        <label>Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Assigned_Task_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>In-Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <masterLabel>Assigned Task Status</masterLabel>
</GlobalValueSet>

classes/RaiseAndCloseProgramCntr.cls
/** Controller for Raise and Close Program component **/
public with sharing class RaiseAndCloseProgramCntr {
    
    /** Returns assigned program details **/
    @AuraEnabled
    public static Assigned_Task__c getProgramDetail(String programId){
        List<String> fields_AT = new List<String>();
        fields_AT.add('Energizers__c');
        fields_AT.add('Feedback__c');
        fields_AT.add('Medals__c');
        fields_AT.add('Current_Value__c');
        fields_AT.add('Milestone__c');
        fields_AT.add('Onboarding_Program__c');
        fields_AT.add('Percentage_Completed__c');
        fields_AT.add('Overdue__c');
        fields_AT.add('Status__c');
        fields_AT.add('Target_Date_Time__c');
        fields_AT.add('Type__c');
        fields_AT.add('Reason_for_Reopen__c');
        fields_AT.add('Assign_To__c');
        List<String> fields_OP = new List<String>();
        fields_OP.add('Name');
        fields_OP.add('Description__c');
        fields_OP.add('Duration__c');
        fields_OP.add('Duration_Type__c');
        fields_OP.add('Duration__c');
        List<String> fields_OT = new List<String>();
        fields_OT.add('Duration__c');
        fields_OT.add('Duration_Type__c');
        fields_OT.add('Name');
        fields_OT.add('Description__c');
        fields_OT.add('Target_Value__c');
        if(FLSCheck.isAccessible(fields_AT,'Assigned_Task__c') && FLSCheck.isAccessible(fields_OP,'Onboarding_Program__c') &&
           FLSCheck.isAccessible(fields_OT,'On_boarding_Task__c')){
               return [SELECT Id,Energizers__c,Feedback__c,Medals__c,
                       Current_Value__c, Milestone__c, Onboarding_Program__r.Name,
                       Onboarding_Program__r.Description__c , Onboarding_Program__r.Duration__c,
                       Onboarding_Program__r.Duration_Type__c,Percentage_Completed__c,
                       Overdue__c,Status__c,Target_Date_Time__c,
                       (SELECT Id,Energizers__c,Medals__c,Reason_for_Reopen__c,
                        Task__r.Duration__c,Task__r.Duration_Type__c,
                        Current_Value__c,Milestone__c,Task__r.Name,
                        Task__r.Description__c,Task__r.Target_Value__c, 
                        Overdue__c,Status__c,Target_Date_Time__c,Task__r.Quantifiable__c 
                        FROM Child_Assigned_Tasks__r)
                       FROM Assigned_Task__c 
                       WHERE Id = :programId 
                       ORDER BY Milestone__c ASC];
           }
        else{
            return null;
        }
    }
}