objects/Assigned_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assign_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Today__c</fullName>
        <formula>DATEVALUE( Target_Date_Time__c) == Today()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Due Today</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Overdue__c</fullName>
        <formula>IF( (TEXT(Status__c) == &apos;In-Progress&apos; || TEXT(Status__c) == &apos;New&apos;) &amp;&amp; (Target_Date_Time__c &lt;  NOW()) ,true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overdue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Assigned_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Assigned Trail</label>
        <referenceTo>Assigned_Task__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Child_Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assigned_Task_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Date_Time__c</fullName>
        <label>Target Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Step</label>
        <referenceTo>On_boarding_Task__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assigned Trail/Step</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Assigned Trail/Step Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Trails/Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Assigned_Task_Contribution__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Assigned Trail/Step Contribution</label>
    <nameField>
        <displayFormat>ATC-{0000}</displayFormat>
        <label>Contribution ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Trail/Step Contributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/On_boarding_Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <label>Onboarding Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Steps</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <label>Business</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Mentor__c</fullName>
        <label>Guide</label>
        <relationshipName>Mentor</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
</CustomObject>

globalValueSets/Assigned_Task_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>In-Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <masterLabel>Assigned Task Status</masterLabel>
</GlobalValueSet>

classes/MentorViewAssignedTaskCntr.cls
 /*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
public class MentorViewAssignedTaskCntr {
    
    @AuraEnabled
    public static Map<String,List<sObject>> getInitData(){
        Map<String,List<sObject>> initData = new Map<String,List<sObject>>();
        List<User> mentees = getMentees();
        initData.put('MENTEES',mentees);
        if(mentees.size() > 0){
            initData.put('MENTEES_CONT',getMenteeCont(mentees.get(0).Id));
        }
        return initData;
    }
    
    private static List<User> getMentees(){
        List<String> fieldNames = new List<String>();
        fieldNames.add('FirstName');
        fieldNames.add('LastName');
        fieldNames.add('Title');
        fieldNames.add('FullPhotoUrl');
        fieldNames.add('MobilePhone');
        fieldNames.add('Email');
        if(FLSCheck.isAccessible(fieldNames,'User')){
            List<User> users = [SELECT Id,FirstName,LastName,Title,FullPhotoUrl,MobilePhone,Email FROM User WHERE Mentor__c = :UserInfo.getUserId()];
            return users;
        }
        return new List<User>();
    }
    
    @AuraEnabled
    public static List<Assigned_Task__c> getMenteeCont(Id menteeUser){
        RecordTypeInfo  businessRecordTypeInfo = Schema.SObjectType.On_boarding_Task__c.getRecordTypeInfosByName().get('Business');
        if(businessRecordTypeInfo.isAvailable()){
            Id businessRecordTypeId = businessRecordTypeInfo.getRecordTypeId();
            List<String> fieldNames_AT = new List<String>();
            fieldNames_AT.add('Due_Today__c');
            fieldNames_AT.add('Target_Date_Time__c');
            //fieldNames_AT.add('Task__c');
            fieldNames_AT.add('Status__c');
            fieldNames_AT.add('Assign_To__c');
            fieldNames_AT.add('Overdue__c');
            List<String> fieldNameTK = new List<String>();
            fieldNameTK.add('Name');
            fieldNameTK.add('Link__c');
            fieldNameTK.add('Task_Due_Date__c');
            fieldNameTK.add('Description__c');
            if(FLSCheck.isAccessible(fieldNames_AT,'Assigned_Task__c') && FLSCheck.isAccessible(fieldNameTK,'On_boarding_Task__c')){
                List<Assigned_Task__c> atc = [SELECT Id,Overdue__c,Due_Today__c,Target_Date_Time__c , 
                                                    Task__r.Name,Task__r.Link__c,Task__r.Description__c ,Status__c,(SELECT Id FROM Child_Assigned_Tasks__r) 
                                                    FROM Assigned_Task__c WHERE Status__c != 'Cancelled' AND Assign_To__c = :menteeUser 
                                                    AND (Task__c =null OR Task__r.RecordTypeId =  :businessRecordTypeId) AND Parent_Assigned_Task__c = null];
                return atc;
            }
        }        
        return new List<Assigned_Task__c>();
    }
    
    @AuraEnabled
    public static Map<String,List<sObject>> getRecordRelateData(String recordId){
        Map<String,List<sObject>> recordRelateData = new Map<String,List<sObject>>();
        List<String> contentDocumentLinkFields = new List<String>();
        contentDocumentLinkFields.add('ContentDocumentId');
        contentDocumentLinkFields.add('LinkedEntityId');
        if(FLSCheck.isAccessible(contentDocumentLinkFields, 'ContentDocumentLink')){
            recordRelateData.put('ATTACHMENTS',[SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :recordId]);
        }
        List<String> assignedTaskContributionFields = new List<String>();
        assignedTaskContributionFields.add('Date__c');
        assignedTaskContributionFields.add('Comments__c');
        //assignedTaskContributionFields.add('Task__c');
        if(FLSCheck.isAccessible(assignedTaskContributionFields, 'Assigned_Task_Contribution__c')){
            recordRelateData.put('TASKCONTRIBUTION',[SELECT Id,Date__c,Comments__c FROM Assigned_Task_Contribution__c]);
        }
        return recordRelateData;
    }
}