objects/Assigned_Task__c.object
<CustomObject>
    <fields>
        <fullName>Onboarding_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Trail</label>
        <referenceTo>Onboarding_Program__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Assigned_Tasks_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assigned Trail/Step</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Assigned Trail/Step Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Trails/Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Onboarding_Program__c.object
<CustomObject>
    <label>Onboarding Trail</label>
    <nameField>
        <label>Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RaiseAndCloseProgramCntr_Test.cls
 /*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 * Test class for RaiseAndCloseProgramCntr 
 */
@isTest
public with sharing class RaiseAndCloseProgramCntr_Test {

    static testMethod void test_getProgramDetail(){
        List<Onboarding_Program__c> onboardingPrograms = TestDataUtil.getOnboardingPrograms(2);
        insert onboardingPrograms;
        User menteeUser = [SELECT Id FROM USER LIMIT 1];
        Assigned_Task__c assignedProgram = TestDataUtil.assignProgramToUser(onboardingPrograms.get(0).Id, menteeUser.Id);
        insert assignedProgram;
        Assigned_Task__c assignedProgramDetail = RaiseAndCloseProgramCntr.getProgramDetail(assignedProgram.Id);
        System.assertEquals(assignedProgram.Id, assignedProgramDetail.Id);
    }
}