objects/Assigned_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assign_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Onboarding_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Trail</label>
        <referenceTo>Onboarding_Program__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Assigned_Tasks_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assigned Trail/Step</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Assigned Trail/Step Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Trails/Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/On_boarding_Task__c.object
<CustomObject>
    <label>Onboarding Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Onboarding_Program__c.object
<CustomObject>
    <label>Onboarding Trail</label>
    <nameField>
        <label>Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Role__c.object
<CustomObject>
    <label>User Role</label>
    <nameField>
        <label>User Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NewOnboardingProgramCntr_Test.cls
/**
 * Test class for NewOnboardingProgramCntr
 **/
@IsTest(SeeAllData=true)
public with sharing class NewOnboardingProgramCntr_Test {
    
    static testMethod void validate_getInit(){
        User_Role__c userRole = TestDataUtil.getUserRole('Software Engineer');
        insert userRole;
        Map<String,List<Object>> initMap = NewOnboardingProgramCntr.getInit();
        System.assertEquals(initMap.get('userRoles').size(),13);
    }
    
    static testMethod void validate_OnboardingnProgramFunctions(){
        List<User> users = [SELECT Id FROM USER WHERE Profile.Name = 'System Administrator' LIMIT 1];
        List<Onboarding_Program__c> onboardingPrograms = TestDataUtil.getOnboardingPrograms(1);
        List<On_boarding_Task__c> onboardingTasks = TestDataUtil.getOnboardingTasks(2);
        insert onboardingTasks;
        User_Role__c userRole1 = TestDataUtil.getUserRole('Software Engineer');
        insert userRole1;
        User_Role__c userRole2 = TestDataUtil.getUserRole('Software Engineer II');
        insert userRole2;
        String selectedRoles = userRole1.Id+';'+userRole2.Id; 
        Onboarding_Program__c insertedProgram = NewOnboardingProgramCntr.insertNewOnboardingProgram(
            JSON.serialize(onboardingPrograms.get(0)),JSON.serialize(onboardingTasks), selectedRoles);
        Onboarding_Program__c retrievedProgram = NewOnboardingProgramCntr.getProgramDetails(insertedProgram.Id);
        System.assertEquals(retrievedProgram.Id, insertedProgram.Id);
        DateTime nowDateTime = DateTime.now();
        NewOnboardingProgramCntr.assignProgram(retrievedProgram.Id,users.get(0).Id,nowDateTime.format('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\''),'Milestone 1');
        List<Assigned_Task__c> assignedTasks = [SELECT Id,Assign_To__c FROM Assigned_Task__c 
                                                       WHERE Onboarding_Program__c = :retrievedProgram.Id];
        for(Assigned_Task__c assignedTask : assignedTasks){
            System.assertEquals(assignedTask.Assign_To__c, users.get(0).Id);
        }
        On_boarding_Task__c onboardingTaskDetail = NewOnboardingProgramCntr.getTaskDetails(onboardingTasks.get(0).Id);
    }
    
}