objects/Assigned_Task__c.object
<CustomObject>
    <fields>
        <fullName>Assign_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Value__c</fullName>
        <label>Current Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Energizers__c</fullName>
        <label>Energizers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Feedback__c</fullName>
        <label>Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Medals__c</fullName>
        <label>Medals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Milestone 1</fullName>
                </value>
                <value>
                    <fullName>Milestone 2</fullName>
                </value>
                <value>
                    <fullName>Milestone 3</fullName>
                </value>
                <value>
                    <fullName>Milestone 4</fullName>
                </value>
                <value>
                    <fullName>Milestone 5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Onboarding_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Trail</label>
        <referenceTo>Onboarding_Program__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Assigned_Tasks_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overdue__c</fullName>
        <formula>IF( (TEXT(Status__c) == &apos;In-Progress&apos; || TEXT(Status__c) == &apos;New&apos;) &amp;&amp; (Target_Date_Time__c &lt;  NOW()) ,true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overdue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Assigned_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Assigned Trail</label>
        <referenceTo>Assigned_Task__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Child_Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Percentage_Completed__c</fullName>
        <label>Percentage Completed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Reason_for_Reopen__c</fullName>
        <label>Reason for Reopen</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Assigned_Task_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Date_Time__c</fullName>
        <label>Target Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Step</label>
        <referenceTo>On_boarding_Task__c</referenceTo>
        <relationshipLabel>Assigned Trails/Steps</relationshipLabel>
        <relationshipName>Assigned_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Quantifiable</fullName>
                </value>
                <value>
                    <fullName>Non-quantifiable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assigned Trail/Step</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Assigned Trail/Step Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Trails/Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/On_boarding_Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration_Type__c</fullName>
        <label>Duration Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hour(s)</fullName>
                </value>
                <value>
                    <fullName>Day(s)</fullName>
                </value>
                <value>
                    <fullName>Week(s)</fullName>
                </value>
                <value>
                    <fullName>Month(s)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Quantifiable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quantifiable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Target_Value__c</fullName>
        <label>Target Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Onboarding Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Steps</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <label>Business</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Onboarding_Program__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration_Type__c</fullName>
        <label>Duration Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hour(s)</fullName>
                </value>
                <value>
                    <fullName>Day(s)</fullName>
                </value>
                <value>
                    <fullName>Week(s)</fullName>
                </value>
                <value>
                    <fullName>Month(s)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Onboarding Trail</label>
    <nameField>
        <label>Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Energizers__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Energizers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Joining_Date__c</fullName>
        <label>Onboarding Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Medals__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Medals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mentor__c</fullName>
        <label>Guide</label>
        <relationshipName>Mentor</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>On_boarding_End_Date__c</fullName>
        <label>On-boarding End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/User_Role__c.object
<CustomObject>
    <label>User Role</label>
    <nameField>
        <label>User Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_User_Role_Junction__c.object
<CustomObject>
    <fields>
        <fullName>User_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Role</label>
        <referenceTo>User_Role__c</referenceTo>
        <relationshipLabel>Users</relationshipLabel>
        <relationshipName>User_User_Role_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_User_Role_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User - User Role Junction</label>
    <nameField>
        <displayFormat>UUR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User - User Role Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Assigned_Task_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>In-Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <masterLabel>Assigned Task Status</masterLabel>
</GlobalValueSet>

classes/MentorProfileCntr.cls
 /*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 *  Controller for Mentor Profile lightning component
 */
public with sharing class MentorProfileCntr {
    
    /**
*  Aura function to return mentor user details along with all mentee users details.
**/
    @AuraEnabled
    public static List<User> getMentorAndBuddiesDetail(){
        List<String> fields_UURJ = new List<String>(); 
        fields_UURJ.add('User_Role__c');
        List<String> fields_UR = new List<String>();
        fields_UR.add('Name');        
        if(FLSCheck.isAccessible(fields_UR,'User_Role__c') && FLSCheck.isAccessible(fields_UURJ,'User_User_Role_Junction__c')){
               return [SELECT Id,FirstName,LastName,FullPhotoUrl,MobilePhone,Email,Energizers__c,Medals__c,
                       Joining_Date__c,On_boarding_End_Date__c,
                       (SELECT Id, User_Role__r.Name FROM User_User_Role_Junctions__r)
                       FROM User WHERE Mentor__c = : UserInfo.getUserId()];
           }
        return new List<User>();
    }
    
    /**
* Wrapper class for Mentee Milestone Information
**/ 
    public class MenteeMilestone{
        @AuraEnabled
        public String milestoneName;
        @AuraEnabled
        public List<Assigned_Task__c> programs;
        @AuraEnabled
        public Boolean milestoneComplete;
        @AuraEnabled
        public Boolean currentMilestone;
        
        public MenteeMilestone(String milestoneName,List<Assigned_Task__c> programs){
            this.milestoneName = milestoneName;
            this.programs = programs;
            this.milestoneComplete = true;
            for(Assigned_Task__c program : programs){
                if(program.Status__c != 'Completed' && program.Status__c != 'Closed'){
                    this.milestoneComplete = false;
                    break;
                }
            }
        }
    }
    
    /** Wrapper class for storing list of Milestones along with current milestone position  **/
    public class MenteeAssignmentInfo{
        @AuraEnabled
        public List<MenteeMilestone> menteeMilestones;
        @AuraEnabled
        public Integer currentMilestonePos = 0;
        
        public MenteeAssignmentInfo(List<MenteeMilestone> menteeMilestones){
            this.menteeMilestones = menteeMilestones;
            for(Integer i=menteeMilestones.size()-1;i>=0;i--){
                if(menteeMilestones[i].milestoneComplete){
                    currentMilestonePos = i+1;
                    menteeMilestones[i].currentMilestone = true;
                    break;
                }
            }
        }
    }
    
    
    /**
* Aura function to return all assigned tasks for a user.
**/
    @AuraEnabled
    public static MenteeAssignmentInfo getMenteeAssignmentInformation(String userId){
        Id businessTaskRecordTypeId = Schema.SObjectType.On_boarding_Task__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        List<MenteeMilestone> menteeMilestons = new List<MenteeMilestone>();
        Map<String,List<Assigned_Task__c>> menteeMilestonesMap = new Map<String,List<Assigned_Task__c>>();
        List<Assigned_Task__c> assignedPrograms = new List<Assigned_Task__c>();
        List<String> fields_AT = new List<String>();
        fields_AT.add('Energizers__c');
        fields_AT.add('Feedback__c');
        fields_AT.add('Medals__c');
        fields_AT.add('Current_Value__c');
        fields_AT.add('Milestone__c');
        fields_AT.add('Onboarding_Program__c');
        fields_AT.add('Percentage_Completed__c');
        fields_AT.add('Overdue__c');
        fields_AT.add('Status__c');
        fields_AT.add('Target_Date_Time__c');
        fields_AT.add('Type__c');
        fields_AT.add('Reason_for_Reopen__c');
        fields_AT.add('Assign_To__c');
        List<String> fields_OP = new List<String>();
        fields_OP.add('Name');
        fields_OP.add('Description__c');
        fields_OP.add('Duration__c');
        fields_OP.add('Duration_Type__c');
        fields_OP.add('Duration__c');
        List<String> fields_OT = new List<String>();
        fields_OT.add('Duration__c');
        fields_OT.add('Duration_Type__c');
        fields_OT.add('Name');
        fields_OT.add('Description__c');
        fields_OT.add('Target_Value__c');
        fields_OT.add('Link__c');
        if(FLSCheck.isAccessible(fields_AT,'Assigned_Task__c') && FLSCheck.isAccessible(fields_OP,'Onboarding_Program__c') &&
           FLSCheck.isAccessible(fields_OT,'On_boarding_Task__c')){
               assignedPrograms = [SELECT Id,Energizers__c,Feedback__c,Medals__c,
                                   Current_Value__c, Milestone__c, Onboarding_Program__r.Name,
                                   Onboarding_Program__r.Description__c , Onboarding_Program__r.Duration__c,
                                   Onboarding_Program__r.Duration_Type__c,Percentage_Completed__c,
                                   Overdue__c,Status__c,Target_Date_Time__c,
                                   (SELECT Id,Energizers__c,Medals__c,Reason_for_Reopen__c,
                                    Task__r.Duration__c,Task__r.Duration_Type__c,
                                    Current_Value__c,Milestone__c,Task__r.Name,
                                    Task__r.Description__c,Task__r.Target_Value__c, 
                                    Overdue__c,Status__c,Target_Date_Time__c,Task__r.Quantifiable__c, 
                                    Task__r.Link__c 
                                    FROM Child_Assigned_Tasks__r WHERE Task__r.RecordTypeId = :businessTaskRecordTypeId)
                                   FROM Assigned_Task__c 
                                   WHERE Assign_To__c  = :userId AND Onboarding_Program__c != null 
                                   ORDER BY Milestone__c ASC];
           }
        for(Assigned_Task__c assignedProgram : assignedPrograms){
            if(assignedProgram.Milestone__c != '' && assignedProgram.Milestone__c != null){
                List<Assigned_Task__c> menteePrograms = new List<Assigned_Task__c>();
                if(menteeMilestonesMap.containsKey(assignedProgram.Milestone__c))
                    menteePrograms = menteeMilestonesMap.get(assignedProgram.Milestone__c);
                menteePrograms.add(assignedProgram);
                menteeMilestonesMap.put(assignedProgram.Milestone__c,menteePrograms);
            }
        }
        for(String milestoneName : menteeMilestonesMap.keySet()){
            menteeMilestons.add(new MenteeMilestone(milestoneName,menteeMilestonesMap.get(milestoneName)));
        }
        
        return new MenteeAssignmentInfo(menteeMilestons);
    }     
    
}