objects/User.object
<CustomObject>
    <fields>
        <fullName>Energizers__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Energizers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Medals__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Medals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mentor__c</fullName>
        <label>Guide</label>
        <relationshipName>Mentor</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Values__c</fullName>
        <label>Values</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Vision__c</fullName>
        <label>Vision</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/User_Role__c.object
<CustomObject>
    <label>User Role</label>
    <nameField>
        <label>User Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_User_Role_Junction__c.object
<CustomObject>
    <fields>
        <fullName>User_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Role</label>
        <referenceTo>User_Role__c</referenceTo>
        <relationshipLabel>Users</relationshipLabel>
        <relationshipName>User_User_Role_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_User_Role_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User - User Role Junction</label>
    <nameField>
        <displayFormat>UUR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User - User Role Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MenteeBibCompCntr.cls
 /*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
public with sharing class MenteeBibCompCntr {
    
    /**
*  Aura function to get Mentor details of the logged in Mentee
**/ 
    @AuraEnabled
    public static User getMentorDetails(){
        List<User> users = [SELECT Id,FirstName,LastName,FullPhotoUrl,Mentor__c,Mentor__r.FirstName,Mentor__r.LastName,
                            Mentor__r.FullPhotoUrl ,Mentor__r.MobilePhone,Mentor__r.Email,
                            Energizers__c,Medals__c,Vision__c,Values__c,
                            (SELECT Id,User_Role__r.Name FROM User_User_Role_Junctions__r)
                            FROM User WHERE Id = : UserInfo.getUserId() LIMIT 1];
        for(User lUser : users){
            return lUser;
        }
        return null;
    }
    
    /** Aura function to update vision and value of Mentee user **/
    @AuraEnabled
    public static Boolean updateVisionAndValues(String values, String vision,String userId){
        try{
            update new User(Id = userId, Vision__c = vision, Values__c = values);
            return true;
        }catch(Exception e){
            return false;
        }
    }
    
}