objects/User.object
<CustomObject>
    <fields>
        <fullName>Energizers__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Energizers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Joining_Date__c</fullName>
        <label>Onboarding Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Medals__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Medals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>On_boarding_End_Date__c</fullName>
        <label>On-boarding End Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/User_Role__c.object
<CustomObject>
    <label>User Role</label>
    <nameField>
        <label>User Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_User_Role_Junction__c.object
<CustomObject>
    <fields>
        <fullName>User_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Role</label>
        <referenceTo>User_Role__c</referenceTo>
        <relationshipLabel>Users</relationshipLabel>
        <relationshipName>User_User_Role_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_User_Role_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User - User Role Junction</label>
    <nameField>
        <displayFormat>UUR-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User - User Role Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MenteeProfileCntr.cls
 /*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
public with sharing class MenteeProfileCntr {
    
    /**
*  Aura function to return mentee user details
**/
    @AuraEnabled
    public static Map<String,Object> getMenteeDetailAndAssignmentInfo(){
        Map<String,Object> returnData = new Map<String,Object>();
        List<String> fields_UURJ = new List<String>(); 
        fields_UURJ.add('User_Role__c');
        List<String> fields_UR = new List<String>();
        fields_UR.add('Name');        
        if(FLSCheck.isAccessible(fields_UR,'User_Role__c') && FLSCheck.isAccessible(fields_UURJ,'User_User_Role_Junction__c')){
               List<User> menteeUsers = [SELECT Id,FirstName,LastName,FullPhotoUrl,MobilePhone,Email,Energizers__c,Medals__c,
                                         Joining_Date__c,On_boarding_End_Date__c,
                                         (SELECT Id, User_Role__r.Name FROM User_User_Role_Junctions__r)
                                         FROM User WHERE Id = : UserInfo.getUserId() LIMIT 1];
               if(menteeUsers.size()>0)
                   returnData.put('MENTEE_INFO',menteeUsers.get(0)); 
               MentorProfileCntr.MenteeAssignmentInfo menteeAssignmentInfo = MentorProfileCntr.getMenteeAssignmentInformation(UserInfo.getUserId());
            returnData.put('ASSIGNMENT_INFO',menteeAssignmentInfo);
           }
        return returnData;
    }
    
}